### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by leesh26** [leesh26/todo-app#1]
### 만들고자 하는 기능이 무엇인가요?
요구사항 명세서 작성

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [ ] 요구사항 초안 작성
2. [ ] 요구사항 상세 작성
3. [ ] 요구사항 별 기한 및 우선순위 작성

### 예상 작업 시간
10h
